import kotlin.time.measureTimedValue

//Overriding getter and setter ( Note that getter and setter are
//automatically generated for us)

fun main() {
    val user = User("Shubham")

    println(user.firstName)

    println("\n")

    user.firstName = "Mohit"

    println("\n")

    println(user.firstName)
}


class User(firstName: String, var lastName: String = "lastname", var age: Int = 0) {
    var firstName = firstName
        get() {  //This is automatically generated by Kotlin for us everytime we define a property
            return "FirstName : $field"
        }
        set(value) {
            println("$value was assigned to firstName property")
            field = value

            //firstName = value     This will call the setter forever . You need to set the field to value
        }

    fun setValue(newValue:String){
        this.firstName = newValue
    }

    fun getValue():String{
        return this.firstName
    }
}